image: node:14

stages:
  - setup
  - code_quality

dependencies:installation:
  stage: setup
  cache:
    paths:
      - node_modules/
  script:
    - npm i --silent
  tags:
    - gitlab-org

lint:scripts:
  stage: code_quality
  cache:
    paths:
    - node_modules/
  script:
    - npm run lint
  only:
    changes:
      - src/**/*.{js}
  tags:
    - gitlab-org
  

